# Generated by Django 3.1.7 on 2021-02-24 12:03

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='modificados',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='modificados',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='modificados',
        ),
        migrations.AddField(
            model_name='cargo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
